name: diabetes-training-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - scikit-learn=1.0.2
  - pandas=1.3.5
  - numpy=1.21.4
  - pip:
    - mlflow==1.26.1
    - mltable==1.0.0
    - azureml-mlflow==1.42.0
