$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: diabetes-training-environment
conda_file: conda.yml
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
