name: Trigger Azure ML Job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS }}
        
    - name: Submit Azure ML Job
      run: |
        az ml job create --file src/job.yml \
          --resource-group adebolaml \
          --workspace-name mlopsdev


