name: Deploy model to endpoint

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Bind job to the right environment
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Azure ML CLI
        run: |
          pip install -U azure-ai-ml azureml-mlflow
      - name: Create deployment YAML dynamically
        run: |
          cat <<EOF > deployment.yml
          name: blue
          endpoint_name: diabetes-endpoint
          model: azureml:diabetes-classifier:1
          model_type: mlflow_model
          instance_type: Standard_B1s
          instance_count: 1
          traffic:
            blue: 100
          EOF

      - name: Deploy latest registered model
        run: |
          ENDPOINT_NAME=diabetes-endpoint
          MODEL_NAME=diabetes-classifier

          # Create endpoint (idempotent - won’t fail if already exists)
          az ml online-endpoint update \
            --name $ENDPOINT_NAME \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}

          # Deploy latest model version
          az ml online-deployment create \
            --file deployment.yml \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}
