name: Deploy model to endpoint

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Bind job to the right environment
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Azure ML CLI
        run: |
          pip install -U azure-ai-ml azureml-mlflow
      - name: Create deployment YAML dynamically
        run: |
          cat <<EOF > deployment.yml
          \$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
          name: blue
          endpoint_name: diabetes-endpoint
          model: azureml:diabetes-classifier:1
          instance_type: Standard_DS3_v2
          instance_count: 1
          EOF

      - name: Deploy latest registered model
        run: |
          set -e
          ENDPOINT_NAME=diabetes-endpoint
          DEPLOYMENT_NAME=blue

          # Ensure endpoint exists (idempotent)
          az ml online-endpoint show \
            --name $ENDPOINT_NAME \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }} \
            || az ml online-endpoint create \
              --name $ENDPOINT_NAME \
              --file endpoint.yml \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}

          echo "🔄 Attempting deployment update..."
          if ! az ml online-deployment update \
            --name $DEPLOYMENT_NAME \
            --endpoint-name $ENDPOINT_NAME \
            --file deployment.yml \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}; then

            echo "⚠️ Update failed — deployment may be in unrecoverable state. Deleting and recreating..."
            az ml online-deployment delete \
              --name $DEPLOYMENT_NAME \
              --endpoint-name $ENDPOINT_NAME \
              --yes \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}

            az ml online-deployment create \
              --name $DEPLOYMENT_NAME \
              --endpoint-name $ENDPOINT_NAME \
              --file deployment.yml \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}
          fi
